name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: macos-latest

    steps:
      - name: Print message
        run: echo "Hello, GitHub Actions!"
      - name: Print bye
        run: echo "bye GitHub Actions!"

  say-hello2:
    runs-on: ubuntu-latest

    steps:
      - name: Print 2nd message
        run: echo "This is Second Message Hii!!"